### ISSUE TITLE
moving forward

### ISSUE THREAD

**Issue by tpapp** [JuliaEditorSupport/julia-ts-mode#32]
Now that #28 is merged and we have a test setup, I am wondering how to move forward with updating this repository.

Here is a proposal about things I would want to do, but I am open to suggestions about other things, and/or the order.

1. Update the grammar. Currently it is 0.23.1, the ["official" repo](https://github.com/tree-sitter/tree-sitter-julia) is at 0.25.0, there is a more up-to-date [fork](https://github.com/tree-sitter-grammars/tree-sitter-julia) by @clason with 0.26.6. I could not find a changelog so we have to figure out what changed from the code, or ask the maintainers.

2. Go though open issues in julia-emacs, see if they are still present with tree-sitter. If not, label those issues with something like `fixed-by-tree-sitter`, we can close them *en masse* at some point when this becomes the recommended solution. #24 should be consulted.

I am pinging maintainers of various repos mentioned, and people who made recent contributions, @savq @clason @dhanak @aviatesk, any advice would be appreciated.

**Comment by clason** [comment]
* https://github.com/tree-sitter/tree-sitter-julia/compare/master...tree-sitter-grammars:tree-sitter-julia:master
* https://github.com/tree-sitter-grammars/tree-sitter-julia/compare/master...tree-sitter%3Atree-sitter-julia%3Amaster

(That fork _is_ maintained; there's just nothing to do right now. But it looks like all our changes have been backported by now.)

Fair warning: There are internal discussions about the future of "upstream" tree-sitter grammar repos; some are under the org because they are used as test fixtures in CI (so there is a desire to have control over them), but many are there simply for historical reasons and nothing but a burden on the current maintainers. I consider the Julia parser to be one of them.

**Comment by dhanak** [comment]
Thanks, @clason, for the heads up. IIUC, we can safely switch over to tree-sitter-grammars/tree-sitter-julia, because this grammar is at least as up-to-date as the original repo, and you have all intentions to keep it this way, too.

**Comment by clason** [comment]
Yes, the fork is a drop-in replacement (meaning queries are fully compatible; I dropped most bindings but can add back individual ones on reasonable request) and currently up-to-date with the upstream project (which I follow, in case there are updates I want to cherry-pick).

**Comment by dhanak** [comment]
Hmm, I'm confused. If the tree-sitter-grammars version is supposedly 0.26.6, then why do package.json and tree-sitter.json still claim "version": "0.23.1"?

**Comment by clason** [comment]
I don't publish my fork, so I don't worry about the **grammar** version.

(Don't confuse the grammar version and the tree-sitter version used to generate it; these are completely independent.)

**Comment by dhanak** [comment]
I asked the AI to summarize changes from 0.23.1 to 0.25.0, and how they affect this codebase. Here's what it said:

v0.25.0 is latest release, dated Nov 8 2025, and GitHub compare shows 35 commits / 46 files changed from v0.23.1 to v0.25.0. Sources: release page and compare page.  (lists.gnu.org (https://lists.gnu.org/r/emacs-devel/2025-04/msg00508.html))

**Must Update**

  - julia-ts-mode.el:46: bump grammar pin only after query fixes.
    Current pin: v0.23.1.

  - julia-ts-mode.el:160: let_binding is gone.
    v0.25.0 removed node types:
    let_binding, named_argument, named_field, scoped_identifier, anonymous "=".
    New node types:
    block, generator.

  - julia-ts-mode.el:165: named_argument is gone.
    Keyword args are now parsed as assignment inside argument_list.
    Existing generic assignment highlighting may now catch keyword args as variables unless adjusted.

  - julia-ts-mode.el:233: second let_binding query also invalid.
    This will make tree-sitter query compilation fail with v0.25.0.

  - julia-ts-mode.el:343: indentation needs visible block.
    v0.25.0 wraps bodies of function, macro, struct, if, for, while, try, begin, quote, etc. in a visible block.
    Current indent rules rely on children being direct under _statement, _definition, _clause. That assumption is now false.

  Likely Update

  - Generator forms now have visible generator nodes. Commit says generators were made visible and _comprehension_clause was replaced by generator.
    Existing el does not directly query for_clause under tuple/argument lists, so not fatal here. Still test multiline generators.

  - macro_identifier shape changed.
    scoped_identifier was hidden/replaced by field_expression for qualified macros. Existing (macro_identifier) @julia-ts-macro-face still compiles, but qualified macro highlighting should be tested.

  - Upstream highlights added/changed:
    pipe call highlighting, updated builtin functions/types, :: handling, modifier keywords, query files for locals.scm and injections.scm.

  Non-el Breaking

  - Parser ABI changed: LANGUAGE_VERSION 14 -> 15.
    Emacs linked against older libtree-sitter may reject ABI 15 grammars. GNU emacs-devel notes pre-0.25 tree-sitter supports ABI up to 14, while tree-sitter 0.25 supports ABI 15. (lists.gnu.org
    (https://lists.gnu.org/r/emacs-devel/2025-04/msg00508.html))
    Docs should warn users to check:
    M-: (treesit-library-abi-version)

  Bottom Line
  Do not only bump the pin. Minimum safe patch:

  1. Replace let_binding queries.
  2. Replace named_argument query with assignment under argument_list.
  3. Prevent keyword-argument assignments from being mis-highlighted as normal LHS variables.
  4. Add visible block indentation handling.
  5. Test font-lock corpus against grammar v0.25.0.
  6. Document ABI 15 caveat.

**Comment by tpapp** [comment]
@clason,

> I don't publish my fork. (Make sure to check the right repository on Github.)

would you mind linking what you think the right repository is? I am now throughly confused.

**Comment by dhanak** [comment]
This ABI version bump from 14 to 15 is something we need to explore in depth: Emacs version 30.1 reports `(treesit-library-abi-version)` to be 14.

**Comment by clason** [comment]
> would you mind linking what you think the right repository is? I am now throughly confused.

Sorry, I thought that was clear since we're only talking about two repositories, one of which is forked from the other. The fork that I am maintaining (that is up-to-date with tree-sitter 0.26.x (which implies ABI 15+, same as upstream HEAD) but does not have a release and hence no new version) is https://github.com/tree-sitter-grammars/tree-sitter-julia, of course.

(And you absolutely want to track tree-sitter (lib) updates in Emacs. You're missing out on crucial bugfixes and significant performance improvements otherwise, and older ABIs _will_ age out eventually. There's about 160 parsers on ABI 15 that I know about alone (which is about half of them).)

**Comment by dhanak** [comment]
So, @clason keeps tree-sitter-grammar up-to-date, but there are no releases, so we can't lock julia-ts-mode to a specific version (as it is done now). In that case, I think I'd prefer to stick to the official release (as long as it exists), and update to version 0.25.0 for now. I'm still concerned about the ABI update, though. I need to understand what that means and what effect it has on earlier versions of Emacs, and if there's a compatibility issue, then can we work around it?

**Comment by clason** [comment]
You can always lock to a specific commit; this is what all other editors do.

(The vast majority of tree-sitter parsers have no release policy -- let alone semver -- so _every_ commit has to be assumed to be breaking.)

**Comment by tpapp** [comment]
I am still figuring out tree-sitter, but I am under the impression that [a number of previous ABI versions can be generated](https://tree-sitter.github.io/tree-sitter/using-parsers/7-abi-versions.html). Specifically, with 15 we can still generate 13.

So the question is: which Emacs version supports at least 13? I am under the impression that 29.1 works with 14, but it needs to be checked.

**Comment by dhanak** [comment]
I have a dream. We, as a community, have at least two de-facto standard tools for formatting Julia code automatically: JuliaFormatter and Runic. The former accepts a configuration file; the latter uses a built-in, opinionated configuration. What if we modified julia-ts-mode such that the user was able to select which formatter to mimic, and in case of JuliaFormatter, it would also parse the configuration file in the project root (if it exists). Then, the mode would adjust its rules to indent the code adhering to these formatting conventions, as much as possible. I'm aware that these formatters do a lot more than indenting, but at least we could copy their indentation rules. WDYT?

**Comment by tpapp** [comment]
I am open to everything but my priority is to get treesitter working and integrate it with julia-mode, so that we can close various issues.

**Comment by dhanak** [comment]
I asked the AI about this ABI compatibility concern. In brief:

- the 0.25 tree-sitter **parser** supports ABI v13-15;
- the 0.25 **generator**, OTOH, can generate ABI v14-15 only;
- the ABI version is fixed in the generated `parser.c`, which is part of the tree-sitter-julia release/distribution/source;
- if we want to support older emacsen with pre 0.25 tree-sitter, we need to maintain an ABI v14 mirror of the tree-sitter-julia source tree.

In slightly more detail:

> Handle it as runtime capability, not Emacs version.
> 
> Best compatibility contract:
> 
> ```text
> Emacs package: loads on Emacs 29.1+
> julia-ts-mode: works when tree-sitter runtime supports needed parser ABI
> grammar target: tree-sitter-julia 0.25.0 parse tree
> ```
> 
> Recommended matrix:
> 
> ```text
> treesit max ABI >= 15  -> use upstream tree-sitter-julia v0.25.0
> treesit max ABI == 14  -> use v0.25.0 regenerated with --abi 14
> treesit max ABI == 13  -> unsupported, fall back to julia-mode / clear error
> ```
> 
> Reason: current CLI docs list ABI 14 as older generation target. ABI 13 is loadable by newer runtimes, but not currently a practical v0.25 generation target per `generate --abi` docs.
> 
> Implementation shape:
> 
> ```elisp
> (defun julia-ts--treesit-abi-max ()
>   (and (fboundp 'treesit-library-abi-version)
>        (treesit-library-abi-version)))
> 
> (defconst julia-ts--grammar-source
>   (let ((abi (julia-ts--treesit-abi-max)))
>     (cond
>      ((and abi (>= abi 15))
>       '(julia "https://github.com/tree-sitter/tree-sitter-julia" "v0.25.0"))
>      ((and abi (>= abi 14))
>       '(julia "https://github.com/JuliaEditorSupport/tree-sitter-julia"
>               "v0.25.0-abi14"))
>      (t nil))))
> ```
> 
> Then only add source when non-nil. For ABI 14, maintain a small fork/tag/branch whose only meaningful difference is regenerated `src/parser.c` with:
> 
> ```sh
> tree-sitter generate --abi 14
> ```
> 
> Typical Emacs package practice:
> 
> - `Package-Requires` covers Lisp API only, e.g. `((emacs "29.1"))`.
> - Native libraries, grammar ABI, executables: checked at runtime.
> - Package load must not fail just because optional native support is absent.
> - Major mode activation may `user-error` with exact missing capability.
> - Use `fboundp`, `boundp`, `treesit-available-p`, `treesit-language-available-p`.
> - Keep docs with external dependency matrix.
> 
> For this package, do not support old grammar and new queries in one path unless you want dual query sets. Cleaner: require v0.25 parse tree; provide ABI15 and ABI14 builds of that grammar; reject ABI13.
> 
> Sources:
> - https://tree-sitter.github.io/tree-sitter/using-parsers/7-abi-versions.html
> - https://tree-sitter.github.io/tree-sitter/cli/generate.html

I also asked about Emacs versions vs. ABI:

>   Emacs 29.1 with tree-sitter enabled supports at least ABI 13.
> 
>   Reason: Emacs 29.1 build accepts tree-sitter >=0.20.2; tree-sitter 0.20.2 supports ABI 13..13.
> 
>   ABI 14 on Emacs 29.1 depends on linked tree-sitter >=0.20.3.
>   ABI 15 depends on linked tree-sitter >=0.25.
> 
>   Check real runtime, not Emacs version:
> 
>   ```elisp
>   (list (treesit-library-abi-version t)
>         `(treesit-library-abi-version))`
>   ```
> 
>   For Julia grammar v0.25.0: best portable target is ABI 14, not 13. It should cover Emacs 29.1 builds linked with tree-sitter 0.20.3+, but not rare/minimal 0.20.2 builds.

**Comment by dhanak** [comment]
@clason, would you care to elaborate on your negative opinion?

**Comment by clason** [comment]
Don't trust AI. Ask the Emacs maintainers responsible for tree-sitter integration instead.

**Comment by tpapp** [comment]
@clason: thanks! what's the best way to reach them, just writing to [emacs-devel](http://lists.gnu.org/mailman/listinfo/emacs-devel)?

**Comment by clason** [comment]
Sorry, I can't help with that, I'm #team(neo)vim. But if there's a main devel mailing list, that's likely the most effective way (unless there's an Emacs Discord server or Matrix channel or whatnot).

**Comment by dhanak** [comment]
> Don't trust AI. Ask the Emacs maintainers responsible for tree-sitter integration instead.

I don't trust the AI any more than I trust a forum post or a random developer on the Internet. That doesn't mean that the AI can be right (and it can be equally wrong), and it's worth considering (and researching) its feedback, esp. on issues I'm not familiar with.

In this particular case, here's what I see:
 
- The `parser.c` in `tree-sitter-grammars/tree-sitter-julia` was generated with ABI 15 (commit [1916f7f](https://github.com/tree-sitter-grammars/tree-sitter-julia/commit/1916f7fe5a670c94224f67dc0f19358828689cdb)).
- GNU Emacs v30.1 on a Debian 13 is built against libtree-sitter.so v0.22.
- According to tree-sitter docs on [ABI versions](https://tree-sitter.github.io/tree-sitter/using-parsers/7-abi-versions.html?highlight=ABI#abi-versions), this tree-sitter library is compatible with parsers using ABI versions 13-14.
- This is confirmed by invoking the elisp expr `(list (treesit-library-abi-version t) (treesit-library-abi-version))`, which returns `(13 14)`.

Based on this, I believe it is correct to assume that the published tree-sitter-julia lib, in its current form, won't be compatible either with Emacs v30 or with v29. Perhaps using a dedicated fork is not the best solution—I don't know yet for sure. But I wouldn't discard it either just because it was suggested by an AI.

**Comment by clason** [comment]
I would like to think I'm not just some "random developer" in this context... Anyway, if current(!) versions of Emacs have such an outdated tree-sitter stack, then that is a bigger issue not specific to Julia and needs to be sorted out by the main developers (asap, because things are only going to get worse since ABI 16 is already in the works).

If Emacs can't upgrade, then you're stuck with either pinning to outdated parsers (and queries!) or adding a local `tree-sitter generate` step into your distribution strategy. (But don't use 0.25.x for that, that's already outdated and missing a huge number of bugfixes.)

**Comment by dhanak** [comment]
I wasn't referring to you specifically as a random developer; I'm sorry if that was the impression.

What you are saying about Emacs in general sounds reasonable. If tree-sitter grammars are mass migrating to this new ABI version, then indeed this could be a problem for ts-based major modes in Emacs in general.

**Comment by clason** [comment]
Oh, they already have, for more than a year -- almost every (active) grammar (that ships a parser) is ABI 15 by now.

(Out of the ~330 that I track for Neovim, 162 are ABI 15, 145 are ABI 14, and 19 are ABI 13 -- with the first ones including most of the "major" languages.)

**Comment by dhanak** [comment]
Here's a table of major Linux distros, corresponding Emacs and linked libtree-sitter versions:

Research snapshot: 2026-07-03.

ABI rule from tree-sitter docs:

```text
0.20.3 through 0.24 -> parser ABI 13-14
0.25+               -> parser ABI 13-15
```

**Package Matrix**

| Distro/release | Emacs | libtree-sitter linked/runtime | Max ABI |
|---|---:|---:|---:|
| Debian 12 bookworm oldstable | 28.2 | no built-in treesit | n/a |
| Debian 13 trixie stable | 30.1 | 0.22.6 | 14 |
| Debian forky testing | 30.2 | 0.26.8 | 15 |
| Ubuntu 22.04 LTS | 27.1 | no built-in treesit | n/a |
| Ubuntu 24.04 LTS | 29.3 | 0.20.8 | 14 |
| Ubuntu 26.04 LTS | 30.2 | 0.25.9 | 15 |
| Ubuntu 25.10 | 30.1 | 0.22.6 | 14 |
| Fedora 43 | 30.2 | 0.25.8 | 15 |
| Fedora 44 | 30.2 | 0.26.8 | 15 |
| Fedora Rawhide | 30.2 | 0.26.9 | 15 |
| RHEL/Rocky/Alma 9 | 27.2 | no built-in treesit | n/a |
| Fedora EPEL 9 lib only | n/a | 0.20.6 | 14 |
| Arch rolling | 30.2 | 0.26.9 | 15 |
| openSUSE Tumbleweed | 30.2 | 0.25.3 | 15 |
| Alpine 3.21 | 29.4 | 0.22.2 | 14 |
| Alpine 3.22 stable | 30.1 | 0.25.10 | 15 |
| Alpine edge | 30.2 | 0.26.7 | 15 |
| Gentoo stable amd64 | 30.2 | 0.26.8, optional `tree-sitter` USE | 15 |

**Implication**

If `julia-ts-mode` jumps to grammar `v0.25.0` and uses upstream ABI 15 parser output, it breaks important still-current systems:

- Ubuntu 24.04 LTS
- Debian 13 stable
- Ubuntu 25.10
- Alpine 3.21

**Comment by clason** [comment]
Ugh, that is even worse than I thought. What a mess. Well, best of luck then; I don't see how you can hope to have any meaningful tree-sitter support without a stable dependency chain...

(But again, this is an Emacs problem. _They_ need to sort this out, otherwise you're wasting your time here.)

**Comment by tpapp** [comment]
@dhanak, thanks for compiling the table. I would use ABI 15 as a the best compromise between maintainer effort and feature availability. First, it's not like our work will be ready tomorrow, so more maybe distributions will catch up in the meantime. Second, the user can always compile Emacs from source, or use a PPA or equivalent, etc.

**Comment by dhanak** [comment]
Out of curiosity (and in preparation), I compiled v0.26.10 (the most recent release) of tree-sitter from source. Then, I downloaded the source of GNU Emacs v30.2 (the latest release), configured it, and tried to compile it with the above tree-sitter version. It doesn't compile.

```
treesit.c: In function ‘treesit_load_language’:
treesit.c:749:42: error: implicit declaration of function ‘ts_language_version’; did you mean ‘ts_language_abi_version’? [-Wimplicit-function-declaration]
  749 |                             make_fixnum (ts_language_version (lang)));
      |                                          ^~~~~~~~~~~~~~~~~~~
      |                                          ts_language_abi_version
make[2]: *** [Makefile:457: treesit.o] Error 1
```

A quick search brought up [this thread](https://lists.gnu.org/archive/html/emacs-devel/2025-09/msg00551.html) on the emacs-devel list from last September. Apparently, Emacs source relies on a function call that was deprecated and removed in tree-sitter v0.26. Therefore, without a patch, it won't compile with anything newer than v0.25.*. But then, @clason above [warned us](https://github.com/JuliaEditorSupport/julia-ts-mode/issues/32#issuecomment-4874671684) against using v0.25.*:

>  (But don't use 0.25.x for that, that's already outdated and missing a huge number of bugfixes.)

It seems that until Emacs itself gets an upgrade, we won't be able to upgrade `julia-ts-mode` to ABI 15.

*Update:* [This issue](https://github.com/tree-sitter/tree-sitter/issues/4968) seems relevant as well, as the author, Eli-Zaretskii of the above email reports this exact problem, and none other than @clason was the first one to respond.

**Comment by clason** [comment]
But your list shows that, e.g., Fedora builds Emacs 30.2 against 0.26.9 (which 0.26.10 is fully compatible with, being a patch release)? I honestly don't understand the situation -- doesn't Emacs have a build script that specifies (and verifies!) which versions of its dependencies it expects?!

But -- again -- this is an Emacs problem and nothing you can do anything about here; you'll have to take whatever the upstream clown college provides. Obviously _this_ project cannot support all ancient Emacs versions with outdated ABI support. You yourself need to do proper versioning with an explicit support matrix, so older Emacs versions need to stick with older versions of this plugin while HEAD targets (only) the latest version. 

(Tree-sitter is _not_ a stable project, so there are _no_ (major) semver guarantees. It's also designed around the use case of a full-stack, statically linked project -- it is _not_ meant to be an independently installed system library, no matter how much distros go "this sign doesn't apply to me because I can't read!")

**Comment by dhanak** [comment]
The distro maintainers probably patched Emacs source, or else got a patched version from somewhere, to make it compile with newer versions of libtree-sitter. I downloaded Emacs source from the official FTP server at <https://ftpmirror.gnu.org/emacs/emacs-30.2.tar.gz>. But since @tpapp [wrote](https://github.com/JuliaEditorSupport/julia-ts-mode/issues/32#issuecomment-4875172940) that “the user can always compile Emacs from source,” I thought I'd give it a go. Well, it's not a smooth ride. I definitely don't want to untangle this knot, nor do I want to get involved in your debate with Emacs developers.

I'll get back to this package when all the building blocks are in place. Until then, grammar v0.23.1 is good enough for me.
